alias: "Activate Relay with Valid QR Code"
trigger:
  - platform: state
    entity_id: sensor.esp32cam_qr_scanned
condition:
  - condition: template
    value_template: >-
      {{ trigger.to_state.state != 'unavailable' and trigger.to_state.state != 'unknown' 
         and trigger.to_state.state == states('input_text.codice_qr_valido') }}
action:
  - service: switch.turn_on
    target:
      entity_id: switch.rele_serratura
  - delay:
      seconds: 5
  - service: switch.turn_off
    target:
      entity_id: switch.rele_serratura
mode: single